name: Flutter CI/CD

on:
  push:
    branches:
      - master
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  upload_to_firebase:
    runs-on: ubuntu-latest
    needs: build_and_deploy

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up credentials
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > $HOME/firebase.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase.json" >> $GITHUB_ENV

#      - name: Set up Google Cloud credentials
#        env:
#          GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
#        run: |
#          echo "$GOOGLE_APPLICATION_CREDENTIALS" > service-account.json
#          gcloud auth activate-service-account --key-file=service-account.json

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app-release.apk \
            --app 1:23225800962:android:56e7803abd2245ee0aca1b  \
            --groups "tester"